config/routes.rb
Rails.application.routes.draw do
  resources :portfolios
  get 'about' , to: 'pages#about'
  get 'content' , to: 'pages#content'
  resources :blogs
  root to: 'pages#home'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  enum status: {draft:0 , published:1}
  extend FriendlyId
  friendly_id :title, use: :slugged
  validates_presence_of :title , :body
  belongs_to :topic
end

app/models/portfolio.rb
class Portfolio < ApplicationRecord
  extend FriendlyId
  friendly_id :subtitle, use: :slugged
  validates_presence_of :title , :body
end

app/models/skill.rb
class Skill < ApplicationRecord
  validates_presence_of :title , :percent
end

app/models/topic.rb
class Topic < ApplicationRecord
  validates_presence_of :title
  has_many :blogs 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy]

  # GET /blogs
  # GET /blogs.json
  def index
    @blogs = Blog.all
  end

  # GET /blogs/1
  # GET /blogs/1.json
  def show
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs
  # POST /blogs.json
  def create
    @blog = Blog.new(blog_params)

    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: 'Blog was successfully created.' }
        format.json { render :show, status: :created, location: @blog }
      else
        format.html { render :new }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogs/1
  # PATCH/PUT /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to @blog, notice: 'Blog was successfully updated.' }
        format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1
  # DELETE /blogs/1.json
  def destroy
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_url, notice: 'Blog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blog_params
      params.require(:blog).permit(:title, :body)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @posts = Blog.all
    @skills = Skill.all
  end

  def about
  end

  def content
  end
end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
  before_action :find_current , only: [:edit,:update,:show,:destroy]
  def params_def
    return params.require(:portfolio).permit(:title,:subtitle,:body)
  end
  def find_current
    @port_items = Portfolio.friendly.find(params[:id])
  end
  def index
    @port_items = Portfolio.all
    #code
  end
  def new
    @port_items = Portfolio.new
    #code
  end
  def edit
  end
  def update
    if @port_items.update(params_def)
      redirect_to portfolios_path
    end
    #code
  end
  def show

    #code
  end
  def destroy
    @port_items.destroy
    redirect_to portfolios_path
    #code
  end
  def create
    @port_items = Portfolio.new(params_def)
    if @port_items.save
      redirect_to portfolios_path
    else
      render :new
    end


  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
end

app/views/blogs/_form.html.erb
<%= form_with(model: blog, local: true) do |form| %>
<% if @blog.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@blog.errors.count, "error") %> prohibited
      this article from being saved:
    </h2>
    <ul>
      <% @blog.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>
  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/blogs/edit.html.erb
<h1>Editing Blog</h1>

<%= render 'form', blog: @blog %>

<%= link_to 'Show', @blog %> |
<%= link_to 'Back', blogs_path %>

app/views/blogs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Blogs</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @blogs.each do |blog| %>
      <tr>
        <td><%= blog.title %></td>
        <td><%= blog.body %></td>
        <td><%= link_to 'Show', blog %></td>
        <td>
          <% if blog.published? %>
            <%= blog.draft!%>
            <% elsif blog.draft? %>
            <%= blog.published! %>
          <% end %>
          <%= link_to blog.status  , notice: 'blog status has been updated' %>
          <%= link_to 'Edit', edit_blog_path(blog) %></td>
        <td><%= link_to 'Destroy', blog, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Blog', new_blog_path %>

app/views/blogs/new.html.erb
<h1>New Blog</h1>

<%= render 'form', blog: @blog %>

<%= link_to 'Back', blogs_path %>

app/views/blogs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @blog.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @blog.body %>
</p>

<%= link_to 'Edit', edit_blog_path(@blog) %> |
<%= link_to 'Back', blogs_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Compproject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/content.html.erb
<h1>Pages#content</h1>
<p>Find me in app/views/pages/content.html.erb</p>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>
<h1>Blog posts</h1>
<%= @posts.inspect %>
<h1>skills list</h1>
<%= @skills.inspect %>

app/views/portfolios/edit.html.erb
<h1>Edit portoflio item</h1>
<%= form_for(@port_items) do |form| %>
  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>
  <div class="field">
    <%= form.label :subtitle %>
    <%= form.text_area :subtitle %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/portfolios/index.html.erb
<h1>Portoflio items</h1>
<% @port_items.each do |item| %>
<h1><%= item.title %></h1>
<p><%= item.subtitle %></p>
<p><%= item.body %></p>
<%= link_to "Edit", edit_portfolio_path(item.id)%>
<a href="portfolios/<%= item.id %>/edit">Edit2</a>
<%= link_to "Create", new_portfolio_path %>
<%= link_to "show" , item %>
<%= link_to "destroy" , item , method: :delete, data: { confirm: 'Are you sure?' }%>
<%= image_tag  item.thumb_image unless item.thumb_image.nil? %>
<% end %>

app/views/portfolios/new.html.erb
<h1>New portoflio item</h1>
<%= form_for(@port_items) do |form| %>
<% if @port_items.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@port_items.errors.count, "error") %> prohibited
      this article from being saved:
    </h2>
    <ul>
      <% @port_items.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
  <% end %>
  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>
  <div class="field">
    <%= form.label :subtitle %>
    <%= form.text_area :subtitle %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/portfolios/show.html.erb
<h1><%= @port_items.title %></h1>
<h2><%= @port_items.subtitle %> </h2>
<p> <%= @port_items.body %></p>
<% if @port_items.main_image? %>
<%= image_tag  @port_items.main_image %>
<% end %>